name: Tural Osman
subtitle: Iqtisadiyyat muellimi ve tedqiqatci
email: turalosmanto9@gmail.com
unec_email: osmanov.tural@unec.edu.az
linkedin: https://www.linkedin.com/in/tural-osmanov-02a137bb/
youtube: https://www.youtube.com/@turalosman391
blog: https://tural-osman.blogspot.com/
